config/routes.rb
Catchlater::Application.routes.draw do
  get "home/index"
  get "bookmarklet" => "home#bookmarklet"
  root to: "home#index"
  resources :videos do
    post "toggle_fave", on: :member
    get "faves", on: :collection
    post "set_tags", on: :member
    get "tagged", on: :collection
    get "tags", on: :collection
    get "feed", on: :collection
    get "bookmark", on: :collection
  end
  resources :users do
    get "forgot_password", on: :collection
    post "send_password_reset", on: :collection, via: :post
    post "set_new_password", on: :member, via: :post
  end
  get "reset_password" => "users#reset_password"
  resource :session
  match "signin" => "sessions#new", as: :signin, via: :get
  match "signout" => "sessions#destroy", as: :signout, via: :get
  get "auth/:provider/callback" => "sessions#create_using_third_party_auth"
  get "auth/failure" => "sessions#new"
  post "sessions/provide_email" => "sessions#provide_email"
end

app/models/user.rb
require 'digest/sha1'
require 'bcrypt'

class User
  include MongoMapper::Document
  include BCrypt
  
  before_create :create_feed_key
  
  key :email,                     String
  key :passwordHash,              String
  key :resetPasswordCode,         String
  key :resetPasswordCodeExpires,  Time
  key :thirdPartyAuthServices,    Hash
  key :feedKey,                   String

  timestamps!

  # Relationships
  has_many :videos, dependent: :destroy
  
  # Validation
  EMAIL_REGEX = /\b[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i
  THIRD_PARTY_SERVICES = %w[facebook twitter]
  THIRD_PARTY_ID_REGEX = /^[0-9a-zA-Z]+$/i

  validates :email, presence: true, uniqueness: true, length: { in: 6..100 },
    format: {with: EMAIL_REGEX, message: "isn't a valid email address"}
  validate :validate_third_party_services
  
  # Retrieves the user for the given email
  # confirms that the password is legit.
  # Returns User instance or nil
  def self.log_in(email, password)
    user = User.first({email: email.downcase})
    user && user.logged_in?(password) ? user : nil
  end
  
  # Checks if the password is valid.
  # Returns Boolean
  def logged_in?(pass)
    password == pass
  end
  
  # Gets the password hash.
  # Returns String or nil if passwordHash isn't present
  def password
    if passwordHash.present?
      @password ||= Password.new(passwordHash)
    else
      nil
    end
  end
  
  # Sets the password hash.
  # newValue should be a String
  # Returns String
  def password=(newValue='')
    @password = newValue
    self.passwordHash = Password.create(newValue)
  end
  
  # Sets the email.
  # Trims and lowercases it.
  # Returns String
  def email=(newEmail)
    newEmail.downcase!
    newEmail.strip!
    write_attribute(:email, newEmail)
  end
  
  # Sends a password reset email
  # and sets resetPasswordCodeExpires
  # and resetPasswordCode.
  def send_password_reset!
    self.resetPasswordCodeExpires = 1.day.from_now
    seed = "#{email}#{Time.now.to_s.split(//).sort_by {rand}.join}"
    self.resetPasswordCode = Digest::SHA1.hexdigest(seed)
    self.save
    UserMailer.password_reset(self).deliver
  end
  
  # Finds a user by a third-party user id on
  # the specified service
  # Returns User or nil if not found
  def self.find_by_third_party_account(service, user_id)
    User.where("thirdPartyAuthServices.#{service}" => user_id).first
  end
  
  private
  
  # Validator for thirdPartyAuthServices.
  # Makes sure only supported services are added
  # and that values are valid user ids.
  def validate_third_party_services
    if !thirdPartyAuthServices.empty?
      thirdPartyAuthServices.each do |key, value|
        if !THIRD_PARTY_SERVICES.include?(key) || !THIRD_PARTY_ID_REGEX.match(value)
          errors.add(:thirdPartyAuthServices, "There's a problem with the #{key} account")
        end
      end
    end
  end
  
  # Sets feedKey before creation.
  def create_feed_key
    write_attribute(:feedKey, Digest::MD5.hexdigest(self.email))
  end

  # Keep feedKey attribute restricted for external assignment.
  def feedKey=(val)
    feedKey = val
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  force_ssl
  # Require login for user-modifiable methods
  before_filter :login_required, only: [:edit, :update, :destroy]
  # redirect logged-in users away from non-logged in methods
  before_filter :redirect_logged_in_user, only: [:new, :create, :send_password_reset, :forgot_password, :reset_password, :set_new_password]

  # New user.
  # Redirects to root path
  # if the user's already
  # logged in.
  def new
    @user = User.new
  end

  # Creates a new user from params.
  # Responds to HTML
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        self.current_user = @user
        format.html { redirect_to videos_url, notice: 'Welcome!' }
      else
        format.html { render 'sessions/new' }
      end
    end
  end

  # Renders user edit view.
  def edit
    @user = current_user
  end

  # Updates the user with the supplied params.
  # Required PUT params: id
  # Responds to HTML, JSON
  def update
    @user = current_user
    respond_to do |format|
      if @user.update_attributes(allowed_params)
        format.html { redirect_to edit_user_path(@user), notice: "You've been updated!" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # Destroys the specified user.
  # Required DELETE params: user
  # Responds to HTML
  def destroy
    @user = current_user
    sign_out_and_kill_session!
    @user.destroy
    redirect_to root_path
  end

  # Sends password reset.
  # Required POST params: email
  # Responds to HTML, JS
  def send_password_reset
    @user = User.first(conditions: {email: params[:email].downcase})
    @user.send_password_reset! if @user
    respond_to do |format|
      format.html { redirect_to forgot_password_users_url, notice: "An email has been sent with password reset instructions" }
      format.js
    end
  end

  # Renders the reset password view
  # if the given values are acceptable.
  # Required GET params: token
  def reset_password
    if !params[:token].present? || !@user = User.first(conditions: {resetPasswordCode: params[:token]})
      error = "The link you used is invalid"
    elsif @user.resetPasswordCodeExpires < DateTime.now
      error = "Whoops! The link you used to reset your password has expired. Please request a new reset email."
    end
    redirect_to(forgot_password_users_url, notice: error) if error
  end

  # Sets a new password for the user
  # filling out the form on #reset_password.
  # Required POST params: token, id
  # Responds to HTML
  def set_new_password
    @user = User.find(params[:id])
    if @user && params[:token].present? && params[:token] == @user.resetPasswordCode
      @user.password = params[:password]
      @user.save
      session[:userId] = @user.id
      redirect_to root_path, notice: "Your new password has been saved"
    else
      redirect_to signin_url, notice: "There was an error with the request"
    end
  end

  protected
  def redirect_logged_in_user
    redirect_to root_path if current_user
  end

  private
  # Allowable params to set via
  # #update mass-assignment.
  def allowed_params
    params[:user].slice(:password)
  end
end

app/views/users/edit.html.erb
<h2>Your Account</h2>

<% if notice %>
<div class="notice"><%= notice %></div>
<% end %>

<section>
	<h3 class="rule">Change your password</h3>
	<%= form_for @user do |form| %>
		<div class="inputWrapper">
			<%= form.label :password, 'Password', class: 'screenReaderOnly' %>
			<%= form.password_field :password, placeholder: 'New password' %>
		</div>
			<%= submit_tag 'Save', data: { disable_with: 'Saving…' } %>
	<% end %>
</section>

<section>
	<h3 class="rule">Close up shop here</h3>
	<i class="icon-trash" role="presentation" aria-hidden="true"></i>
	<%= link_to "Delete your account", user_path(@user), data: { confirm: "Are you sure?" }, method: "delete", class: "delete" %>
</section>

app/views/users/forgot_password.html.erb
<h2>Get a new password</h2>

<p>Enter your email address and you'll receive an email with instructions to set a new password.</p>

<%= form_tag send_password_reset_users_path do %>
	<div class="inputWrapper">
		<%= label_tag 'email', 'Email', class: 'screenReaderOnly' %>
		<%= email_field_tag :email, nil, placeholder: 'Your email' %>
	</div>
	<%= submit_tag 'Send It', data: { disable_with: 'Sending…' } %>
<% end %>

app/views/users/new.html.erb
  <%= render partial: "sessions/sign_up" %>

app/views/users/reset_password.html.erb
<h2>Set A New Password</h2>

<% if notice %>
<div class="notice"><%= notice %></div>
<% end %>

<%= form_tag set_new_password_user_path(@user) do %>
	<div class="inputWrapper">
		<%= label_tag 'password', 'New Password', class: 'screenReaderOnly' %>
		<%= password_field_tag :password, nil, placeholder: 'New password' %>
		<%= hidden_field_tag 'token', params[:token] %>
	</div>
	<%= submit_tag 'Save', data: { disable_with: 'Saving…' } %>
<% end %>

app/views/users/send_password_reset.js.erb
$('form').prepend('<p class="highlight center">An email has been sent with password reset instructions</p>')