config/routes.rb
Catchlater::Application.routes.draw do
  get "home/index"
  get "bookmarklet" => "home#bookmarklet"
  root to: "home#index"
  resources :videos do
    post "toggle_fave", on: :member
    get "faves", on: :collection
    post "set_tags", on: :member
    get "tagged", on: :collection
    get "tags", on: :collection
    get "feed", on: :collection
    get "bookmark", on: :collection
  end
  resources :users do
    get "forgot_password", on: :collection
    post "send_password_reset", on: :collection, via: :post
    post "set_new_password", on: :member, via: :post
  end
  get "reset_password" => "users#reset_password"
  resource :session
  match "signin" => "sessions#new", as: :signin, via: :get
  match "signout" => "sessions#destroy", as: :signout, via: :get
  get "auth/:provider/callback" => "sessions#create_using_third_party_auth"
  get "auth/failure" => "sessions#new"
  post "sessions/provide_email" => "sessions#provide_email"
end

app/models/video.rb
class Video
  include MongoMapper::Document

  key :videoID,     String, required: true
  key :webpageUrl,  String, required: true
  key :type,        String, required: true
  key :source,      String, required: true
  key :title,       String
  key :tags,        Array
  key :favorited,   Boolean, default: false
  key :user_id,     ObjectId

  timestamps!

  belongs_to :user

  URL_REGEX = /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix
  SUPPORTED_SOURCES = %w[youtube vimeo ted npr gamespot mtv dailymotion blip mixergy videobam nbc liveleak ign nytimes]
  TYPES = %w[iframe video object embed]

  validates :webpageUrl, format: {
    with: URL_REGEX,
    message: "The web page's URL is invalid"
  }
  validates :source, inclusion: {
    in: SUPPORTED_SOURCES,
    message: "Sorry, your source %{value} isn't supported"
  }
  validates :type, inclusion: {
    in: TYPES,
    message: "The type of video isn't supported"
  }

  def self.find_by_tag(tag)
    all(tags: ["#{tag}"])
  end

  def self.for_user(current_user, condition = {}, page_number = 1)
    self.paginate(page: page_number || 1, conditions: condition.merge({user_id: current_user.id}), order: 'created_at DESC', per_page: 3)
  end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
  before_filter :loginRequired
  
  def new
    @video = Video.new
  end
  
  def add
    @video = Video.new
    @video.user = currentUser
    if @story.save
  end
  
  def remove
    @video = Video.find_by_id(params[:id])
    @video.destroy
  end
  
  def index
    
  end
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  force_ssl except: [:feed]
  # Ensure the user's logged in
  # #bookmark sends its own response to unauthenticated users
  # #feed provides an atom feed of videos for the user's
  # md5-ed email address
  before_filter :login_required, except: [:bookmark, :feed]
  # Ensure that the user owns the video that's being requested
  before_filter :ensure_user_owns_video, only: [:show, :toggle_fave, :destroy, :set_tags]

  # New view.
  # Renders the view
  def new
    @video = Video.new
  end

  # Creates a new view from the supplied post params.
  # Responds to HTML, JSON
  def create
    @video = Video.new(params[:video])
    @video.user = current_user
    respond_to do |format|
      if @video.save
        format.html { redirect_to root_path }
        format.json { render json: @video }
      else
        format.html { render :action => :new }
        format.json { render json: @video.errors }
      end
    end
  end

  # Renders a video.
  # Required GET params: id
  # Responds to HTML, JSON
  def show
    respond_to do |format|
      format.html
      format.json { render json: @video }
    end
  end

  # Toggles the specified video's 'favorited'
  # field. Flips its current state rather than
  # accepting a state to set.
  # Required POST params: id
  # Responds to HTML, JS, JSON
  def toggle_fave
    @video.favorited = !@video.favorited
    respond_to do |format|
      if @video.save
        format.html { redirect_to :back }
        format.js
        format.json { render json: @video }
      end
    end
  end

  # Destroys the specified video.
  # Required DELETE params: id
  # Responds to HTML, JS, JSON
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_path }
      format.js
      format.json { head :ok }
    end
  end

  # Renders all non-favorited videos.
  # Optional GET params: page
  # Responds to HTML, JS
  def index
    @page = (params[:page] || 1).to_i
    @videos = VideoDecorator.decorate_collection(Video.for_user(current_user, {favorited: false}, @page))
    get_tags_for_current_user
    respond_to do |format|
      format.js
      format.html
    end
  end

  # Renders all favorited videos.
  # Optional GET params: page
  # Responds to HTML, JS
  def faves
    @page = (params[:page] || 1).to_i
    @videos = VideoDecorator.decorate_collection(Video.for_user(current_user, {favorited: true}, @page))
    get_tags_for_current_user
    respond_to do |format|
      format.js
      format.html
    end
  end

  # Sets tags on the specified video.
  # Tags are simply set, rather than
  # appended, so all tags should always
  # be specified.
  # Required POST params: id, tags
  #  `tags` should be a comma-separated
  #  list of strings.
  # Responds to JSON
  def set_tags
    @video.tags = params[:tags].strip.split(',').uniq
    @video.save
    invalidate_tags_for_current_user
    render json: @video.tags
  end

  # Renders all tags for
  # the user's videos.
  def tags
    get_tags_for_current_user
  end

  # Renders all videos tagged with the
  # given string.
  # Required GET params: with
  # Optional GET params: page
  # Responds to JS, HTML
  def tagged
    @tag = params[:with]
    @page = (params[:page] || 1).to_i
    @videos = VideoDecorator.decorate_collection(Video.for_user(current_user, {tags: @tag}, @page))
    get_tags_for_current_user
    respond_to do |format|
      format.js
      format.html
    end
  end

  # Renders all videos as an atom feed.
  # Required GET params: key
  def feed
    @user = User.first(conditions: {feedKey: params[:key]})
    raise ActionController::RoutingError.new('Not Found') if !@user

    @videos = VideoDecorator.decorate_collection(Video.all(conditions: {user_id: @user.id})) || []
    @title = "CatchLater: videos for #{@user.email}"

    respond_to do |format|
      format.atom
    end
  end

  # JSONP request made from bookmarklet.
  def bookmark
    if current_user
      @video = Video.new(params.slice(:videoID, :webpageUrl, :type, :source, :url))
      @video.user = current_user
      if @video.save
        render_jsonp @video.to_json
      else
        logger.debug @video.errors.inspect
        render_jsonp @video.errors.to_json
      end
    else
      render_jsonp Hash[login_required: true].to_json
    end
  end

  protected
  # Makes sure that the user owns the video
  def ensure_user_owns_video
    @video = Video.find(params[:id])
    return render :error, status: 404 if @video.nil?
    return render :error, status: 403 if @video.user != current_user
    @video = VideoDecorator.decorate(@video)
  end

  private

  # Retrieves the tags for all of the user's videos
  # and sets it as an instance variable.
  # Checks for view fragment caching.
  # TK - replace with Redis
  def get_tags_for_current_user
    unless fragment_exist?("#{current_user.id}/tags")
      @tags = UserVideoTags.get(current_user.id)
    end
  end

  # Expires the tag view fragment cache.
  def invalidate_tags_for_current_user
    expire_fragment("#{current_user.id}/tags")
  end
end

app/helpers/videos_helper.rb
module VideosHelper
  def share_link(label, url)
    link_to url, target: "_blank", title: "Share on #{label.capitalize}" do
      share_icon label
    end
  end

  def share_icon(label)
    raw "<i class='icon-#{label}' aria-hidden='true' role='presentation'></i><span class='screenReaderOnly'>#{label.capitalize}</span>"
  end

  def full_date(date)
    date.strftime("%B %e %Y, %l:%M %p %Z")
  end

  def created_date(date)
    if (date < 5.days.ago)
      date.strftime("%b %e")
    else
      time_ago_in_words(date) + ' ago'
    end
  end

  def equivalent_urls(a_url, b_url)
    URI.split(a_url).slice(1, 8) == URI.split(b_url).slice(1, 8) rescue false
  end

  def source_url(url, truncate_size = 20)
    url.gsub(/http(s)?:\/\/(www.)?/, '').truncate(truncate_size)
  end
end

app/views/videos/_heading.html.erb
<h2>
  <%= heading ||= "Your list" %>
  <% if defined? rss %>
  <a class='icon-rss' href="<%= rss_path %>"><span class='screenReaderOnly'>RSS Feed</span></a>
  <% end %>
</h2>
<% if empty %>
<% emptyMessage = "Videos will appear here" if current_user.created_at > 2.days.ago %>
<h3><%= emptyMessage ||= "There's nothing here :-|" %></h3>
<% end %>

app/views/videos/_share.html.erb
<span class="shareDropdown hide">
	<ul>
    <li>
      <%= share_link 'facebook', "http://www.facebook.com/sharer.php?u=#{url_encode(videoUrl)}" %>
    </li>
		<li>
      <%= share_link 'twitter', "http://twitter.com/home?status=#{url_encode(videoUrl)}" %>
    </li>
		<li>
      <%= share_link 'tumblr', "http://www.tumblr.com/share?v=3&u=#{url_encode(videoUrl)}" %>
    </li>
		<li>
      <%= mail_to "", subject: "Shared Video", body: "\n\n#{videoUrl}", title: "Email a link" do %>
      <%= share_icon "email" %>
      <% end %>
    </li>
  <% if equivalent_urls(sourceUrl, videoUrl) %>
    <li class="source only-source"><%= link_to source_url(videoUrl, 45), videoUrl, title: videoUrl, target: "_blank" %></li>
  <% else %>
    <li class="source"><%= link_to source_url(videoUrl), videoUrl, title: videoUrl, target: "_blank" %></li>
		<li class="source"><%= link_to source_url(sourceUrl), sourceUrl, title: sourceUrl, target: "_blank" %></li>
  <% end %>
	</ul>
</span>

app/views/videos/_tag_list.html.erb
<% if defined? visible %>
<ul class="tagList">
<% else %>
<ul class="tagList hide">
<% end %>
<% cache "#{@current_user.id}/tags", skip_digest: true do %>
  <% tags.each do |tag| %>
    <li class="tag">
      <a href="<%= tagged_videos_path %>?with=<%= tag[:name] %>">
        <span class="name"><%= tag[:name] %></span>
      <span class="count">(<%= tag[:count].to_i %>)</span>
    </a>
    </li>
  <% end %>
<% end %>
</ul>

app/views/videos/_video.html.erb
<div id="<%= video.id %>" class="video" data-page="<%= @page %>">
	<span class="title">
		<%= video.title %>
	</span>
	<div class="content <%= video.source %>">
		<% if video.embed? %>
		<video src="<%= video.video_url %>" controls preload="none" poster="<%= video.poster %>">
			Your browser doesn't support this type of video :(
		</video>
		<% else %>
		<iframe src='<%= video.embed_url %>' allowfullscreen></iframe>
		<% end %>
		<%= link_to toggle_fave_video_path(video),
					class: "fave" + ((video.favorited) ? " selected" : ""),
					title: "Favorite this video",
					remote: true,
					method: :post do
		%>
			<span class="screenReaderOnly">Favorite</span>
		<% end %>
	</div>
	<span class="aux">
		<span class="date" title="<%= full_date(video.created_at) %>"><%= created_date(video.created_at) %></span>
		<span class="actions">
			<%= link_to video_path(video), class: "action delete icon-trash", title: "Delete", data: { confirm: "Are you sure?" }, method: :delete, remote: true do %>
				<span class="screenReaderOnly">Delete</span>
			<% end %>
			<%= link_to video_path(video), class: "action pip icon-popup", title: "Open in a new window" do %>
				<span class="screenReaderOnly">Open in a new window</span>
			<% end %>
			<%= link_to "javascript:void(0)", class: "action share icon-export", title: "Share" do %>
				<span class="screenReaderOnly">Share</span>
			<% end %>
			<%= render partial: "share", locals: { videoUrl: video.link(), sourceUrl: video.webpageUrl } %>
		</span>
	</span>
	<span class="tags">
		<%= form_tag set_tags_video_path(video) do %>
			<label>
				Tags
				<input type="text" name="tags" class="tagEntry" value="<%= video.tags.join(',') %>"/>
			</label>
			<input type="submit" value="Submit" class="screenReaderOnly"/>
		<% end %>
	</span>
</div>

app/views/videos/destroy.js.erb
$("#<%= @video.id %>").slideUp("slow", function() {
	$(this).remove()
});

app/views/videos/error.html.erb
<div class="cf">
  <h2>Oh Noes</h2>
</div>

<p>You aren't allowed to perform this action.</p>

app/views/videos/faves.html.erb
<%= render partial: "heading", locals: { 
					 heading: "Your favorites",
					 emptyMessage: "You haven't favorited anything yet",
           empty: @videos.empty?
} %>
<%= render partial: "nav", locals: { tags: @tags } %>

<section class="faves videoList">
	<%= render @videos %>
</section>

app/views/videos/faves.js.erb
<%= render(@videos) %>

app/views/videos/index.html.erb
<% content_for :rss do %>
  <%= auto_discovery_link_tag :atom, rss_path %>
<% end %>

<%= render partial: "heading", locals: { empty: @videos.empty?, rss: true } %>
<%= render partial: "nav", locals: { tags: @tags } %>

<% if notice %>
<div class="notice"><%= notice %></div>
<% end %>

<% if @videos.empty? %>
<%= render partial: "shared/bookmarklet", locals: { heading: "Start saving videos while you browse the web." } %>
<% else %>
<section class="queue videoList">
	<%= render @videos %>
</section>
<% end %>

app/views/videos/index.js.erb
<%= render(@videos) %>

app/views/videos/new.html.erb
<h2>Add a new video</h2>
<% if @video.errors.any? %>
  <ul>
    <% @video.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @video do %>
	<div>
		<%= label_tag 'videoID', 'Video ID', class: 'screenReaderOnly' %>
		<%= text_field_tag :videoID, nil, placeholder: 'Video id' %>
	</div>
	<div>
		<%= label_tag 'webpageUrl', 'Website page URL', class: 'screenReaderOnly' %>
		<%= url_field_tag :webpageUrl, nil, placeholder: 'Webpage URL' %>
	</div>
	<div>
		<%= label_tag 'type', 'Type', class: 'screenReaderOnly' %>
		<%= text_field_tag :type, nil, placeholder: 'Type' %>
	</div>
	<div>
		<%= label_tag 'source', 'Source', class: 'screenReaderOnly' %>
		<%= text_field_tag :source, nil, placeholder: 'Source' %>
	</div>
	<%= submit_tag 'Add', data: { disable_with: 'Adding…' } %>
<% end %>

app/views/videos/show.html.erb
<section>
  <%= render @video %>
</section>

app/views/videos/tags.html.erb
<h2>Your tags</h2>

<%= render partial: "nav", locals: { tags: @tags } %>
<%= render partial: "tag_list", locals: { tags: @tags, visible: true } %>

app/views/videos/toggleFave.js.erb
$("#<%= @video.id %> .fave").toggleClass("selected");