config/routes.rb
Catchlater::Application.routes.draw do
  get "home/index"
  get "bookmarklet" => "home#bookmarklet"
  root to: "home#index"
  resources :videos do
    post "toggle_fave", on: :member
    get "faves", on: :collection
    post "set_tags", on: :member
    get "tagged", on: :collection
    get "tags", on: :collection
    get "feed", on: :collection
    get "bookmark", on: :collection
  end
  resources :users do
    get "forgot_password", on: :collection
    post "send_password_reset", on: :collection, via: :post
    post "set_new_password", on: :member, via: :post
  end
  get "reset_password" => "users#reset_password"
  resource :session
  match "signin" => "sessions#new", as: :signin, via: :get
  match "signout" => "sessions#destroy", as: :signout, via: :get
  get "auth/:provider/callback" => "sessions#create_using_third_party_auth"
  get "auth/failure" => "sessions#new"
  post "sessions/provide_email" => "sessions#provide_email"
end

app/views/shared/_bookmarklet.html.erb
<div class='bookmarklet'>
  <h2><%= heading ||= "Save videos for later while you browse the web." %></h2>
  <%= content_tag :a, "CatchLater", onclick: "alert('Drag this button to the bookmarks bar')", href: bookmarklet, class: 'button' %>
  <div>
    <aside><span id='hand'>☝</span> Drag this button up to your bookmarks bar</aside>
  </div>
  <div class='instructions'>
    <%= bookmarklet_instructions %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <ul>
    <li><a href='/faq'>FAQ</a></li>
    <li><a href='/privacy'>Privacy</a></li>
    <li><a href='/about'>About</a></li>
    <li><a href='/bookmarklet'>Bookmarklet</a></li>
  </ul>
</footer>

app/views/shared/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="Save online videos across the web for later viewing">
  <meta id="viewport" name="viewport" content="initial-scale=1.0,user-scalable=no,minimum-scale=1.0,maximum-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes">
	<link href='/favicon.ico' rel='icon' type='image/x-icon'>
	<title>CatchLater</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <link href="//fonts.googleapis.com/css?family=Molengo:regular|News+Cycle|Sue+Ellen+Francisco" rel="stylesheet" type="text/css">
  <%= csrf_meta_tag %>
  <%= yield :rss %>
</head>

app/views/shared/_header.html.erb
<header>
	<h1><a href="/">CatchLater</a></h1>
	<span id="helloAgain">
		<% if current_user %>
		<span class='greeting'>
      Hello, <%= link_to current_user.email, edit_user_path(current_user.id), :class => 'userLink' %>.
    </span>
		<%= link_to "Sign out", signout_path, :class => 'signout' %>
		<% end %>
	</span>
</header>