config/routes.rb
Catchlater::Application.routes.draw do
  get "home/index"
  get "bookmarklet" => "home#bookmarklet"
  root to: "home#index"
  resources :videos do
    post "toggle_fave", on: :member
    get "faves", on: :collection
    post "set_tags", on: :member
    get "tagged", on: :collection
    get "tags", on: :collection
    get "feed", on: :collection
    get "bookmark", on: :collection
  end
  resources :users do
    get "forgot_password", on: :collection
    post "send_password_reset", on: :collection, via: :post
    post "set_new_password", on: :member, via: :post
  end
  get "reset_password" => "users#reset_password"
  resource :session
  match "signin" => "sessions#new", as: :signin, via: :get
  match "signout" => "sessions#destroy", as: :signout, via: :get
  get "auth/:provider/callback" => "sessions#create_using_third_party_auth"
  get "auth/failure" => "sessions#new"
  post "sessions/provide_email" => "sessions#provide_email"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home', :except => :bookmarklet
  
  def index
    redirect_to videos_url if current_user
  end

  def bookmarklet
    render action: 'bookmarklet', layout: 'application'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/bookmarklet.html.erb
<div class='bookmarklet'>
  <h2>Save videos for later while you browse the web.</h2>
  <div class='buttonArea'>
    <p></p>
    <%= link_to "CatchLater", "alert('Drag this button to the bookmarks bar')", href: bookmarklet, class: 'button' %>
    <div>
      <aside><span id='hand'>☝</span> Drag this button up to your bookmarks bar</aside>
    </div>
  </div>
  <div class='instructions'>
    <%= bookmarklet_instructions %>
  </div>
</div>

app/views/home/index.html.erb
<div id="top">
	<div class="screen" role="presentation"></div>
	<div class="vid">
		<video autoplay loop muted preload="auto" width="100%" height="100%" poster="//s3.amazonaws.com/catchlater/poster.jpg">
			<source src="//s3.amazonaws.com/catchlater/park.webm" type="video/webm">
			<source src="//s3.amazonaws.com/catchlater/park.mp4" type="video/mp4">
			<source src="//s3.amazonaws.com/catchlater/park.ogg" type="video/ogg">
		</video>
	</div>
	<div class="words">
		<h1>CatchLater</h1>

		<section class="existingSignin">Already a user? <%= link_to "Sign in", signin_path %></section>

		<section class="teaser">
			<p>Save videos from around the web in a single queue.</p>
			<p>It's totally free. It's totally awesome.</p>
		</section>

		<%= link_to "Sign up!", signin_path, class: "signup" %>
	</div>
</div>

<div id="bottom">
	<section>
		<h2><em>See</em> a video</h2>
		<caption>Looks good, but you don't have time or aren't in the mood.</caption>
		<div><img class="sample-1" src="<%= asset_path('sample.jpg') %>" alt="Long video that's inconvenient to watch just now"></div>
	</section>

	<section>
		<h2><em>Save</em> for later</h2>
		<caption>Just click a handy bookmarklet. And now it's saved for later viewing right here.</caption>
		<div><img class="sample-2" src="<%= asset_path('sample.jpg') %>" alt="Click a bookmarklet"></div>
	</section>

	<section>
		<h2><em>Popcorn</em> time</h2>
		<caption>Watch that video when you have time. Works great on your phone or tablet!</caption>
		<div><img class="sample-3" src="<%= asset_path('sample.jpg') %>" alt="Watch the video later"></div>
	</section>
</div>